spring.application.name=actionhouse
# Servidor
server.port=8080

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/actionhouse
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC
spring.jdbc.template.query-timeout=30

# Logs utiles en desarrollo
logging.level.org.springframework.jdbc=DEBUG
# Subida de imágenes
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads
# Cloudinary
cloudinary.cloud-name=dnwppuipe
cloudinary.api-key=369528622247399
cloudinary.api-secret=0U57tge-hDaEOosNLLYeyzZM684